export const SEARCH_LOCATION_BUTTON_CLICKED = "SEARCH_LOCATION_BUTTON_CLICKED"
export const VIEW_WEATHER_FORECAST = "VIEW_WEATHER_FORECAST"
export const CLOSE_WEATHER_FORECAST = "CLOSE_WEATHER_FORECAST"